### ISSUE TITLE
Error while executing role for the first time: "Could not find the requested service"

### ISSUE THREAD

**Issue by Savidude** [wso2/ansible-apim#35]
**Description:**
Needs to be fixed by moving the 

```
- name: Copy WSO2APIM service file
   template:
     src: "wso2apim.service.j2"
     dest: /etc/systemd/system/wso2is.service
```

Block to before the server is being stopped at 
```
- name: Stop wso2apim as a service
   systemd:
     name: wso2apim
     state: stopped
```

**Suggested Labels:**
Type/Bug
Priority/High

**Suggested Assignees:**
@Savidude
