### ISSUE TITLE
JDK unzipping failure 

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/ansible-apim#79]
**Description:**
Sometimes the JDK archive name is different from the extracted folder name. Current Ansible scripts expect them to be the same.

**Possible Fix**
```
- name: Unzip JDK
  unarchive:
    src: /path/to/jdk.tar.gz
    dest: /path/to/extract/{{ jdk_name }}
    extra_opts: [--strip-components=1]
```
