### ISSUE TITLE
Deprecation warning "evaluating enable_performance_tuning as a bare variable" when running on Ansible 2.8.0

### ISSUE THREAD

**Issue by Savidude** [wso2/ansible-apim#80]
**Description:**
The following warning is encountered when running the Ansible playbook.

```
[DEPRECATION WARNING]: evaluating enable_performance_tuning as a bare variable, this behaviour will go away and you might need to add
|bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed in version
2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Can be fixed by changing the conditional checking if performance tuning is enabled to a Boolean value.
```
- name: System performance tuning
  copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   loop: "{{ performance_tuning_file_list }}"
   when: enable_performance_tuning|bool
```

**Suggested Labels:**
Type/Bug
Priority/Low

**Suggested Assignees:**
@Savidude
